spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
frontend.url=${FRONTEND_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
gemini.api.key=AIzaSyCCbBJT5kejPfM0YHUky9iySwNwi-Lyl_0
jwt.secret=MySuperSecretKeyForJWTToken123456789!!!
jwt.expirationMs=86400000

client.origin=http://localhost:3000